Repository INMalyshev/BMSTU-TEAM-DEV-2024, pull requests merged in 2024-04, with the labels that each got.

#14 Создать скелет структуры проекта #9
  .flakeignore
  .gitignore
  LICENSE.txt
  Pipfile
  Pipfile.lock
  makefile
  readme.md
  setup.py
  src/cards/__init__.py
  src/cards/core/__init__.py
  src/cards/core/ping.py
  test/cards/core/test_ping.py
Labels: tech

#15 Выполнить базовую настройку CI/CD в github репозитории #10
  .github/workflows/ci-cd.yml
  .gitignore
  readme.md
Labels: CI/CD

#20 create business logic
  src/cards/__init__.py
  src/cards/core/__init__.py
  src/cards/core/cardset_repository_abc.py
  src/cards/core/cardset_service.py
  src/cards/core/constants.py
  src/cards/core/exceptions.py
  src/cards/core/model.py
  src/cards/core/validators.py
  test/cards/core/test_validators.py
Labels: tech

#21 Add sqlite data
  src/cards/__init__.py
  src/cards/core/__init__.py
  src/cards/sqlite_data/__init__.py
  src/cards/sqlite_data/cardset_repository.py
  src/cards/sqlite_data/db_handler.py
  src/cards/sqlite_data/mappers.py
  src/cards/sqlite_data/utils.py
  test/cards/sqlite_data/integration/test_cardset_repository.py
Labels: tech

#27 Fix doc strings format
  src/cards/core/cardset_repository_abc.py
  src/cards/core/cardset_service.py
Labels: improvement

#17 Docs gen and deployment
  .github/workflows/docs-gen.yml
  docs/Makefile
  docs/make.bat
  docs/source/api.rst
  docs/source/conf.py
  docs/source/core.rst
  docs/source/db.rst
  docs/source/index.rst
  src/cards/core/cardset_repository_abc.py
  src/cards/core/cardset_service.py
  src/cards/core/ping.py
Labels: CI/CD, improvement

#30 readme improvements
  makefile
  readme.md
Labels: improvement

#31 Develop
  makefile
  readme.md
Labels: reliz

#32 Release/release 0.0.1
  makefile
  readme.md
Labels: reliz
